const { ethers } = require("ethers");
require("dotenv").config();

const RPC_URL = process.env.RPC_URL || process.env.SEPOLIA_RPC_URL || "http://127.0.0.1:7545";
const PRIVATE_KEY = process.env.PRIVATE_KEY;
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS;

if (!PRIVATE_KEY || !CONTRACT_ADDRESS) {
    console.warn("Blockchain config missing: PRIVATE_KEY or CONTRACT_ADDRESS not found in .env");
}

let contract;

try {
    const provider = new ethers.JsonRpcProvider(RPC_URL);
    const wallet = new ethers.Wallet(PRIVATE_KEY, provider);

    // Load ABI from the artifacts generated by Hardhat
    const artifactPath = "../../blockchain/artifacts/contracts/NGOFund.sol/NGOFund.json";
    const artifact = require(artifactPath);

    contract = new ethers.Contract(CONTRACT_ADDRESS, artifact.abi, wallet);
    console.log("Blockchain connected to contract:", CONTRACT_ADDRESS);
} catch (error) {
    console.error("Failed to initialize blockchain connection:", error.message);
    // We might want to handle this gracefully if blockchain is optional
}

module.exports = contract;
